plugins {
    id 'java-library'
    id 'io.qameta.allure' version '3.1.0'
}

allure {
    report {
        version = '2.20.0'
    }
    adapter {
        aspectjWeaver = true
        frameworks {
            junit5 {
                adapterVersion = '2.20.0'
            }
        }
    }
}

repositories {
    mavenCentral()
}

dependencies {
    testImplementation 'org.junit.jupiter:junit-jupiter:5.10.0'
    testImplementation 'com.codeborne:selenide:7.14.0'
    testImplementation 'com.github.javafaker:javafaker:1.0.2'
    testImplementation 'com.codeborne:pdf-test:1.5.0'
    testImplementation 'com.codeborne:xls-test:1.4.3'
    testImplementation 'com.opencsv:opencsv:5.12.0'
    testImplementation 'com.fasterxml.jackson.core:jackson-databind:2.21.2'
    testImplementation 'org.junit.platform:junit-platform-launcher'
}

test {
    useJUnitPlatform()
}